# Generated by Django 4.2 on 2023-12-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
        ),
    ]
