# Generated by Django 4.2 on 2023-12-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
        ),
    ]
